### ISSUE TITLE
Add instructions on how to use Sphinx to example workflow

### ISSUE THREAD

**Issue by peanutfun** [CMakePP/CMinx#109]
**Is your feature request related to a problem? Please describe.**
The [Example Workflow](https://cmakepp.github.io/CMinx/full_example.html) page in the docs demonstrates very verbosely how different comment blocks are transformed into RST. However, the workflow falls short of showing how to get an actual documentation from the RST. I realize that this can all be looked up in the Sphinx documentation but I think it would be helpful for users that *do not* have a RST toctree already. Since CMake is mostly used for C/C++ and Sphinx is typically used to document Python code, chances are high that users don't have a working Sphinx setup in their build.

**Describe the solution you'd like**
Extend the example workflow with instructions for creating a Sphinx build. I did it the following way:
* Install Sphinx.
* Create a sub-directory in the project build directory.
* Enter this directory and call `sphinx-quickstart`. Follow the instructions.
* Run `cminx` on the project and set the sub-directory as output directory.
* Create an index RST file with a toctree (This is not technically needed, but otherwise you just get a module index).
* Run `sphinx-build` in that directory.

Since the "translation" from CMake comments to RST is demonstrated a lot in other parts of the docs, the example could also be shortened to improve the readability of the doc page.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ryanmrichard** [comment]
I think this is a great idea. I'll go ahead and work on it now.

**Comment by ryanmrichard** [comment]
@peanutfun sorry should have pinged you regarding #114. When you get a chance take a look at #114 and let me know if that addresses your concerns and/or if there's more that should be added.
