### ISSUE TITLE
Consolidate "setup.cfg", "pyproject.toml", and "requirements.txt"

### ISSUE THREAD

**Issue by peanutfun** [CMakePP/CMinx#110]
**Is your feature request related to a problem? Please describe.**
This project defines its package information via three different configuration files, namely `setup.cfg`, `pyproject.toml`, and `requirements.txt`. All three files can be consolidated into a single file, preferably into `pyproject.toml` (see https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)

**Describe the solution you'd like**
Only use `pyproject.toml` and merge contents of `setup.cfg` and `requirements.txt` into it. As far as I understand, `requirements.txt` only contains the requirements for testing. This can be handled, e.g., via [optional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) to make this destinction clear.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ryanmrichard** [comment]
Thanks for the info! This is the first PyPI package I've ever made (I'm primarily a C++ developer), so I'm definitely still learning. I can take a stab at this one too.
