### ISSUE TITLE
Could you add an example for the `FetchContent` solution to the documentation? I think this would be very helpful, as the CMake modules would become available to users.

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMinx#117]
Could you add an example for the `FetchContent` solution to the documentation? I think this would be very helpful, as the CMake modules would become available to users.

_Originally posted by @peanutfun in https://github.com/CMakePP/CMinx/pull/104#discussion_r963695211_

**Comment by peanutfun** [comment]
Depending on how much information it is, this could also be added to the README

**Comment by ryanmrichard** [comment]
@peanutfun when you get a chance, please take a look at #119 and see if that helps.
