### ISSUE TITLE
Add "Edit on GitHub" button to CMinx documentation webpage

### ISSUE THREAD

**Issue by robertodr** [CMakePP/CMinx#122]
**Is your feature request related to a problem? Please describe.**
It is currently possible to see the sources for the documentation webpages, but to edit one needs to get to the repo and browse it to find the correct file. This is a bit inconvenient if one just wants to quickly suggest a fix to a typo.

**Describe the solution you'd like**

It should be possible to configure the documentation build process to link back the rendered page to its sources on GitHub.

**Describe alternatives you've considered**

Current system works, but it could be streamlined.

**Additional context**

This is related to the JOSS review process https://github.com/openjournals/joss-reviews/issues/4680

**Comment by ryanmrichard** [comment]
To be honest, I never noticed that we didn't have the "edit on GitHub" button. I thought that was there by default. Nonetheless, #125 (hopefully) fixes this issue. At the very least #125 gets the button, I won't know until it's merged whether the links actually work though. My plan is to keep working on #125 until we get the button and working links. This issue will close in the process, but feel free to reopen if after I'm done with #125 the button isn't working.

**Comment by robertodr** [comment]
It appears to work now. Thanks!
