### ISSUE TITLE
[Question] Is it possible to document bare `add_test` calls

### ISSUE THREAD

**Issue by robertodr** [CMakePP/CMinx#123]
**Before opening this issue I:**

- [X] Checked the documentation for answers
- [X] Looked for similar issues
- [X] Did a quick internet search

The documentation (https://cmakepp.github.io/CMinx/documenting/cmaketest.html) shows how it's possible to document the test suite when using the wrappers provided by CMakeTest. Is the same possible if one uses vanilla `add_test` instead?

**Comment by AutonomicPerfectionist** [comment]
Hi @robertodr! It is possible to document regular CTest `add_test()` calls, however they will show up in the documentation as generic command invocations. I can add explicit support for them soon so they show up in the documentation better. Thanks for the question/suggestion!
