### ISSUE TITLE
[BUG] Release and Tag not triggering.

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMinx#138]
**Describe the bug**
PIP release and tag didn't happen on the last merge (#137)

**To Reproduce**
Presumably by merging another PR into master which should trigger tagging and release.

**Comment by AutonomicPerfectionist** [comment]
Looking at the workflow it seems most of the work is done by other actions in CMakePP, but in our workflow we don't have a specific version selected and are going off main. Could be that those actions have updated and now don't work for us

**Comment by ryanmrichard** [comment]
The upstream action looks the same. AFAIK [tag_and_release.yaml](https://github.com/CMakePP/CMinx/blob/master/.github/workflows/tag_and_release.yaml) never even ran; so it didn't get a chance to even call the upstream action.

**Comment by AutonomicPerfectionist** [comment]
Hmmm... I see that now, wonder why... Looking at the `on` clause it should've run.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard looks like the `deploy_docs` workflow hasn't executed either, it has the same `on` clause as the the tag and release workflow. Wonder if how that works has been changed in the last few weeks

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard I can't seem to figure out the problem at all, would you be able to trigger the actions manually for now? I don't seem to have access to do that

**Comment by ryanmrichard** [comment]
I just reran the last run of `tag_and_release.yaml` and nothing happened.

**Comment by ryanmrichard** [comment]
I made a trivial change to the README. That at least got the documentation to build.

**Comment by AutonomicPerfectionist** [comment]
After testing the action locally with Act I've found that the release job is being skipped because the outputs from the `tag` job are not matching `true` when they should. Setting the outputs manually in the `tag` job by adding a step and commenting out the `tag_and_release_master` action allowed `release` to trigger correctly. The linked issue describes a possible cause for this change in behavior
