### ISSUE TITLE
Escape special ReST characters in parameter names

### ISSUE THREAD

**Issue by zachcran** [CMakePP/CMinx#154]
**Is your feature request related to a problem? Please describe.**
When documenting a variable list of arguments for a function, `*args` and `**kwargs` are used in Python. Since CMinx is trying to encourage Pythonic documentation, the same parameter names should be used, like `:param *args:`. However, when `*args` is used as a parameter name, Sphinx will complain about `WARNING: Inline emphasis start-string without end-string.`

**Describe the solution you'd like**
When CMinx parses parameter names, I would like it to escape ReST special characters like `*`. ~This would also be an issue if you prefix a parameter with underscores, which is done frequently in CMaize.~

**Describe alternatives you've considered**
The user can also escape all of these characters themselves, but IIRC you don't need to do this when writing Python docstrings, so I would prefer not to here as well.

**Additional context**
You can see the warnings yourself by trying to build the CMakePPLang documentation. Here are the steps to do so:
1. Install CMinx: `python -m venv venv; source venv/bin/activate; pip install CMinx`
2. Grab CMakePPLang source: `git clone https://github.com/CMakePP/CMakePPLang.git`
3. Navigate into CMakePPLang: `cd CMakePPLang`
4. Generate the API documentation:
```bash
cminx \
    cmake/cmakepp_lang \
    -o docs/source/api/generated_docs \
    -r
```
5. Build the documentation with Sphinx: `cd docs; make html`

Edit: Underscores are not inline markup characters in ReST... that was Markdown, sorry!

**Comment by AutonomicPerfectionist** [comment]
As far as I am aware, you do need to escape the asterisks for Python by default, there are extensions that allow you to ignore the escaping for specifically `*args` and `**kwargs` but they aren't default. Additionally, CMinx is generating the exact same RST that would be generated for Python (ignoring the Autodocs extension). 

It would be possible to auto-escape asterisks inside of parameters, I would probably go with a simple regex search and replace. I would like to caution against too much preprocessing of the docstring though, we don't currently have an RST parser available to CMinx, and with more preprocessing that parser is going to become a necessity.

**Comment by ryanmrichard** [comment]
FWIW, I would expect any automatically generated RST (as opposed to docstrings dumped verbatim) to be generated in a warning free manner. Doesn't CMinx generate the literal `**kwargs` that gets placed in the RST documentation? If so, then I feel like we should generate it in an escaped form, whereas if it's the user who writes the literal `**kwargs`, not us, then I think they should have to escape it themselves (or use the extensions you mentioned).  

I agree we don't want to do too much pre-processing of the docstring, less we start going down an RST parser rabbit hole (and AFAIK there's actually several flavors of RST, which makes this more complicated...).

@zachcran I guess I haven't written Python documentation in a while; if the user isn't supposed to escape things in the docstrings don't you just end up with a ton of warnings?

**Comment by zachcran** [comment]
I guess I was misremembering then! I can just find and replace to escape them.

**Comment by AutonomicPerfectionist** [comment]
> Doesn't CMinx generate the literal `**kwargs` that gets placed in the RST documentation?

I haven't seen any warnings related to that but I think it's because the asterisks are paired and not inside another structure. I can definitely check though
