### ISSUE TITLE
Always use `/` in toctree (also on Windows)?

### ISSUE THREAD

**Issue by tobiasleibner** [CMakePP/CMinx#161]
CMinx uses `toctree.text(os.path.join(directory, "index.rst"))` ([here](https://github.com/CMakePP/CMinx/blob/51558674c3d9bf1f3afaef48bd66b3f74aefb028/src/cminx/__init__.py#L283)) to insert the the index files in the toctree. On Windows, this results in, e.g.,
```rst

#####
Title
#####

.. toctree:: 
   :maxdepth: 2

   subfolder\index.rst
   cmakefile1
   cmakefile2
```
with a backslash as path separator. When reading this file, Sphinx gives the following warning:
```
sphinx.errors.SphinxWarning: C:\...\build\win_msvc\docs\Debug\sphinx_src\cmake\index.rst:6:toctree contains reference to nonexisting document 'folder/subfolder\\index'
```
Replacing the backward by a forward slash, i.e., `subfolder/index.rst` instead of `subfolder\index.rst` fixes the problem.

I could not find a definite reference for that but it looks like the paths in the toctree should always use a forward slash?

**Comment by ryanmrichard** [comment]
I just did a couple searches myself. While I also can't find an authoritative source there seems to be enough issues about needing "/" on Windows to suggest that using `os.path.join` is wrong. I should have some free time in the next couple hours to try to fix this.
