### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMinx#25]
Apparently there is already a project called CMakeDoc and it's in PIP (https://github.com/agateau/cmakedoc). We should rename this repo to avoid confusion.

**Comment by AutonomicPerfectionist** [comment]
Running a search on multiple search engines yields zero results for "cmakeppdoc", would that name work or would it cause confusion with the other CMakePP project (https://github.com/toeb/cmakepp)? Alternatively, we could try "cmdoc" or "cmkdoc", but both of those are a little too abstract/hard to interpret for my liking.

**Comment by ryanmrichard** [comment]
I'm hoping to move to more memorable names for the project (i.e., stop calling things CMakePPX). The idea is that CMakePP is the language/organization. To that end, how about `CMinx`?  A mashup of CMake and Sphinx.

**Comment by AutonomicPerfectionist** [comment]
Cminx sounds good, would you like me to update the references to match that?

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist that sounds good. Thanks.

**Comment by AutonomicPerfectionist** [comment]
Fixed with #27, should be able to be closed now.
