### ISSUE TITLE
Typo in `README.md`

### ISSUE THREAD

**Issue by dschiller** [CMakePP/CMinx#29]
At https://github.com/CMakePP/CMinx/blob/master/README.md

Is
==

Usage
------
For each CMake function or variable that you would like to document, prepend it with a block doc-comment. A block doc-comment begins with `#[[[` and ends with `#]]`.

Should be
=======

Usage
------
For each CMake function or variable that you would like to document, prepend it with a block doc-comment. A block doc-comment begins with `#[[` and ends with `#]]`.

**Comment by ryanmrichard** [comment]
I don't think this is a typo.

Would the following make this more clear:

## Usage

For each CMake function or variable that you would like to document, prepend it with a block doc-comment. A block doc-comment begins with `#[[[` and ends with `#]]`. Note that block *doc*-comments start with an extra `[` to distinguish them from normal block comments (which start with `#[[`). Normal block comments are ignored by CMinx while parsing, whereas block doc-comments will be used to generate reStructuredText documentation.

**Comment by dschiller** [comment]
You are right Ryan. I like your new version better, makes it clear and removes confusion.
