### ISSUE TITLE
Add verbose mode

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMinx#72]
**Is your feature request related to a problem? Please describe.**
We need a way to get more debugging information. This is motivated by #70.

**Describe the solution you'd like**
I vote we add a `-v,--verbose` flag to CMinx which controls the printing. I'm thinking it would for starters print status updates for:

- the name of the file about to be parsed
- the name of the file about to be generated

I'd also recommend making CMinx silent by default and make it so the current printing is part of the verbose mode.

**Describe alternatives you've considered**
None

**Comment by AutonomicPerfectionist** [comment]
This would be the perfect time to move CMinx to a proper logging framework instead of using basic `print()` calls

**Comment by ryanmrichard** [comment]
We can close this issue if you like. I opened it before you added the logger. I think the logging options you mentioned already have are a better option.
