### ISSUE TITLE
Pandoc

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMinx#78]
https://pandoc.org/

It might be possible to support a variety of markup languages by using pandoc.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard not sure Pandoc can do anything for us here; we're tightly coupled with Sphinx-flavored RST since we use many of its directives, and they won't be translated across languages with pandoc unless they are processed by Sphinx first.

**Comment by ryanmrichard** [comment]
Thanks for looking into this.
