### ISSUE TITLE
Format according to PEP8

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CMakePP/CMinx#88]
**Is your feature request related to a problem? Please describe.**
Python has a very specific format specification described in [Python Enhancement Proposal 8](https://peps.python.org/pep-0008/). Nowadays this specification is considered the standard Python code format, and most IDEs support autoformatting files to PEP8.

**Describe the solution you'd like**
A quick format using autoPEP8 or an IDE equivalent, and adherence to the standard for future code additions.

**Describe alternatives you've considered**
We could come up with our own formatting rules and implement them as a custom formatter profile. However this would introduce significant effort to create the profiles for each major IDE or tool, for minimal benefits compared to using PEP8

**Comment by ryanmrichard** [comment]
IMHO PEP8 is the way to go. I'd recommend setting up a CI action to do it. Basically when a user submits a PR, the action runs autopep8 on it, and pushes the changes to the PR. It probably can be done using the [apply_license](https://github.com/CMakePP/.github/blob/main/.github/workflows/add_licenses_master.yaml) workflow as a template.

**Comment by AutonomicPerfectionist** [comment]
I thought about a CI action as well but I'm worried it could introduce errors. My IDE's formatter kind of garbled triple-quoted strings but running autopep8 manually didn't seem to do the same thing, so I'm hoping it won't be an issue
